docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
  - Introduction: intro.md
  - 'Quick Start': quick-start.md
  - 'ICS Export': export-ics.md
  - Tutorials:
    - 'Integrate to Outlook': outlook.md
site_name: oneplace-skeleton
site_description: "onePlace Event Module"
repo_url: 'https://github.com/OnePlc/PLC_X_Event'
theme: bootstrap4
extra:
  project: onePlc