<?php

$this->InlineScript()
    ->appendFile('/vendor/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js');

$this->headLink()
    ->appendStylesheet('/vendor/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css')
    ->appendStylesheet('/vendor/oneplace-event/css/colorpicker.css');

/**
 * Generate Card to Import Calendar
 */
$sCardBody = $this->partial('partial/event/calendar/import_body', []);
$sCardFooter = $this->partial('templates/card/basic_footer', [
    'sButtonLabel' => $this->translate('Create Calendar'),
    'sButtonIcon' => 'fas fa-save',
    'bCancelButton' => true,
    'sCancelButtonAction' => '/calendar',
    //'sCancelButtonClass' => 'btn-danger',
]);
?>
<form action="" method="POST">
<?php
echo $this->partial('templates/card/basic', [
    'sCardTitle' => $this->translate('Create new Calendar'),
    'sCardBody' => $sCardBody,
    'sCardFooter' => $sCardFooter,
]);
?>
</form>

<script>
$(function () {
    $('.plc-colorpick').colorpicker({
        inline: false,
        container: true,
        autoInputFallback: false,
        format: 'hex',
        customClass: 'colorpicker-2x',
        sliders: {
            saturation: {
                maxLeft: 200,
                maxTop: 200
            },
            hue: {
                maxTop: 200
            },
            alpha: {
                maxTop: 200
            }
        }
    });

   $('input[name="calendar_type"]').on('change', function () {
       let sType = $(this).val();
       if(sType == 'local') {
           $('.calendar-internet').addClass('d-none');
           $('.calendar-local').removeClass('d-none');
           $('.plc-card-savebutton').html('<i class="fas fa-save"></i> Create Calendar');
       } else {
           $('.calendar-local').addClass('d-none');
           $('.calendar-internet').removeClass('d-none');
           $('.plc-card-savebutton').html('<i class="fas fa-download"></i> Import Calendar');
       }
   });
});
</script>