<form action="" method="POST">
    <?php
    /**
     * Generate Card to Import Calendar
     */
    $sCardBody = $this->partial('partial/event/calendar/import_body', []);
    $sCardFooter = $this->partial('partial/basic_card_footer', [
        'sButtonLabel' => $this->translate('Import Calendar'),
        'sButtonIcon' => 'fas fa-download',
        'bCancelButton' => true,
        'sCancelButtonAction' => '/calendar',
        //'sCancelButtonClass' => 'btn-danger',
    ]);

    echo $this->partial('partial/basic_card', [
        'sCardTitle' => $this->translate('Import Calendar'),
        'sCardBody' => $sCardBody,
        'sCardFooter' => $sCardFooter,
    ]);
    ?>
</form>