<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 05.07.2019
 * Time: 20:49
 */

?>
<div class="row">
    <div class="col-md-2">
        <h3><?=$this->translate('Calendars')?></h3>
        <ul class="list-group">
            <?php foreach($aCalendars as $oCal) { ?>
                <li class="list-group-item">
                    <span class="btn btn-primary" style="background:<?=$oCal->getColor('background')?>; color:<?=$oCal->getColor('text')?>;"><?=$oCal->getLabel()?></span>
                </li>
            <?php }?>
        </ul>
    </div>
    <div class="col-md-10">
        <div id='calendar'></div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: [ 'dayGrid', 'timeGrid', 'list', 'bootstrap','interaction'],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
            },
            eventClick: function(info) {
                $.post('/event/modal/'+info.event.id,{mode:'modal',goto:'general'},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });
            },
            dateClick: function(info) {
                var sDateSelected = info.dateStr;
                $.get('/event/modal/0',{mode:'modal',goto:'general',date:sDateSelected},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });
            },
            locale: 'de',
            weekNumbers: true,
            themeSystem: 'bootstrap',
            defaultDate: '<?=date('Y-m-d',time())?>',
            navLinks: true, // can click day/week names to navigate views
            editable: true,
            eventLimit: true, // allow "more" link when too many events
            eventSources: <?=json_encode($aEventSources)?>
        });

        calendar.render();

        <?php if($dJump != '') { ?>
        calendar.gotoDate('<?=$dJump?>');
        <?php } ?>

        <?php
        if($iEventSelID != 0) { ?>
        $.post('/event/modal/<?=$iEventSelID?>',{mode:'modal',goto:'general'},function(retModal) {
            $('#exampleModalCenter').html(retModal);
            $('#exampleModalCenter').modal('toggle');
        });
        <?php } ?>
    });
</script>
