<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 05.07.2019
 * Time: 20:49
 */

$this->InlineScript()
    ->appendFile($this->basePath() . '/vendor/oneplace-event/lib/@fullcalendar/main.min.js')
    ->appendFile($this->basePath() . '/vendor/oneplace-event/lib/@fullcalendar/locales-all.min.js')
    ->appendFile('https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js');

$this->headLink()
    ->appendStylesheet($this->basePath() . '/vendor/oneplace-event/lib/@fullcalendar/main.min.css')
    ->appendStylesheet('https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css')
?>
<div class="row">
    <div class="col-md-2">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    <?=$this->translate('Calendars')?>
                </h2>
            </div>
            <div class="card-body p-0 b-0">
                <ul class="list-group">
                    <?php foreach($aCalendars as $oCal) { ?>
                        <li class="list-group-item p-0">
                        <div class="btn btn-primary w-100" style="border:1px solid <?=$oCal->getColor('background')?>; background:<?=$oCal->getColor('background')?>; color:<?=$oCal->getColor('text')?>;">
                            <div class="row">
                                <div class="col-md-8 text-left">
                                    <div style="font-size:18px;">
                                        <?=$this->translate($oCal->getLabel())?>
                                        <?=($oCal->is_remote == 1) ? '<i class="fas fa-cloud"></i> ' : ''?>
                                    </div>
                                </div>
                                <div class="col-md-4 text-right">
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle text-white" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-cog"></i>
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                            <a class="dropdown-item" href="/calendar/share/<?=$oCal->getID()?>">
                                                <i class="fas fa-share"></i> Teilen</a>
                                            <a class="dropdown-item" href="/calendar/settings/<?=$oCal->getID()?>">
                                                <i class="fas fa-cog"></i> Einstellungen</a>
                                            <a class="dropdown-item" href="#">
                                                <i class="fas fa-trash"></i> Löschen</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </li>
                    <?php }?>
                </ul>
            </div>
            <div class="card-footer">
                <a class="btn btn-light" href="/calendar/importical" title="<?=$this->translate('Add Calendar')?>">
                    <i class="fas fa-cloud"></i> <?=$this->translate('Add Calendar')?>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        <div id='calendar'></div>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
</div>
<script>

    document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'timeGridWeek',
            navLinks: true, // can click day/week names to navigate views
            //editable: true,
            defaultDate: '<?=date('Y-m-d',time())?>',
            locale: 'de',
            weekNumbers: true,
            //themeSystem: 'bootstrap', buggy as of 2021-03-28 - switching back to default system for now
            eventClick: function(info) {
                $.post('/event/modal/'+info.event.id,{mode:'modal',goto:'general'},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });
            },
            dateClick: function(info) {
                var sDateSelected = info.dateStr;
                $.get('/event/modal/0',{mode:'modal',goto:'general',date:sDateSelected},function(retModal) {
                    $('#exampleModalCenter').html(retModal);
                    $('#exampleModalCenter').modal('toggle');
                });
            },
            eventSources: <?=json_encode($aEventSources)?>
        });
        calendar.render();

        <?php if($dJump != '') { ?>
        calendar.gotoDate('<?=$dJump?>');
        <?php } ?>

        <?php
        if($iEventSelID != 0) { ?>
        $.post('/event/modal/<?=$iEventSelID?>',{mode:'modal',goto:'general'},function(retModal) {
            $('#exampleModalCenter').html(retModal);
            $('#exampleModalCenter').modal('toggle');
        });
        <?php } ?>
    });
</script>
<style>
    <?php foreach($aCalendars as $oCal) { ?>
    .dot-<?=$oCal->getID()?> {
        height: 20px;
        width: 20px;
        margin-right:4px;
        background-color: <?=$oCal->color_background?>;
        border-radius: 50%;
        display: inline-block;
    }
    <?php } ?>
</style>
