<?php

?>
<form action="" method="POST">
    <?php
    /**
     * Generate Card to Manage Settings
     */
    $sCardBody = $this->partial('partial/event/calendar/share_body', [
        'oCalendar' => $oCalendar,
    ]);
    $sCardFooter = $this->partial('partial/basic_card_footer', [
        'bCancelButton' => true,
        'sCancelButtonAction' => '/calendar',
        'sCancelButtonLabel' => $this->translate('Back to Calendar'),
    ]);

    echo $this->partial('partial/basic_card', [
        'sCardTitle' => $this->translate('Share Calendar'),
        'sCardBody' => $sCardBody,
        'sCardFooter' => $sCardFooter,
    ]);
    ?>
</form>

<script>
    $(function () {
        $('#shareCalendarToUser').select2({
            placeholder: 'Add New User',
            ajax: {
                url: '/user/api/list/0',
                dataType: 'json'
            }
        });

        $('#shareCalendarToUser').on('select2:select', function(e) {
            let sName = e.params.data.text;
            $('#calendarShareList').append('<li class="list-group-item"><div class="row"> <div class="col-md-4 col-lg-2"> '+sName+' </div><div class="col-md-4 col-lg-2"><span class="badge badge-primary badge-lg">Admin</span></div><div class="col-md-4 col-lg-2"><a href="#"><i class="fas fa-edit"></i></a> | <a href="#"><i class="fas fa-trash"></i></a></div></div></li>');
        });
    });
</script>